name = "syncheartist"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "syncheartist-db"
database_id = "af601b1b-bb80-45a7-b431-2abfc8bc78df"
